version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ${Dockerfile}
      args:
      - APPLICATION_PORT=${APPLICATION_PORT}
      - DOCKER_CONTAINER=true     
    ports:
      - ${APPLICATION_PORT}:${APPLICATION_PORT}
    depends_on:
      - postgres
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: ${POSTGRES_LOGGING}

volumes:
  postgres_data:
    name: postgres_data_${DB_NAME}